/**
 * <pre>
 * - Project   : Ebook Online - Cloud Accounting Platform
 * - Package   : com.ntaganira.heritier.ibook.service
 * - File      : DocumentStorage.java
 * - Date      : 2026. 09. 25.
 * - User      : Hntaganira
 * - Desc      : Where the bytes of an uploaded document actually live
 * </pre>
 */
package com.ntaganira.heritier.ibook.service;

import org.springframework.core.io.Resource;
import org.springframework.web.multipart.MultipartFile;

/**
 * Keeps the choice of store behind one interface.
 *
 * <p>The database holds the <em>metadata</em> — who uploaded what, when, and which record it
 * belongs to — and a storage key. The bytes live wherever an implementation of this puts them.
 * That split is the point: a five-megabyte scan of a receipt inside a table row makes every backup
 * of the books carry it too, and there is no reason for a query about attachments to drag file
 * contents through memory.
 *
 * <p>{@link FileSystemDocumentStorage} is the only implementation today. A MinIO one would satisfy
 * this same interface without touching the entity, the service or a single page.
 */
public interface DocumentStorage {

    /**
     * Writes the bytes and returns the key they can be read back by. The key is generated by the
     * store; the caller's filename is never part of it.
     */
    Stored store(MultipartFile file);

    Resource load(String storageKey);

    boolean exists(String storageKey);

    /** Returns false when there was nothing there, rather than throwing. */
    boolean delete(String storageKey);

    /** Where the store is putting things, so the page can say it out loud. */
    String describeLocation();

    record Stored(String storageKey, long sizeBytes, String checksum) {}
}
